export const STUDENT_ROLE = 1;
export const RECRUITER_ROLE = 2;
export const SKILLS = [
  { id: "180", name: "AGILE SCRUM" },
  { id: "276", name: "ANALYSIS DESIGN" },
  { id: "101", name: "ANDROID" },
  { id: "113", name: "ARTICULATE" },
  { id: "138", name: "ARTIFICIAL INTELLIGENCE" },
  { id: "89", name: "AWS" },
  { id: "17", name: "Accredited Pension Representative" },
  { id: "61", name: "Active Listening" },
  { id: "119", name: "Adobe" },
  { id: "273", name: "Advanced Software Engineer" },
  { id: "87", name: "Agile" },
  { id: "107", name: "AngularJS" },
  { id: "357", name: "Antivirus" },
  { id: "386", name: "Asic Design Engineer" },
  { id: "345", name: "Associate Software Design Engineer" },
  { id: "405", name: "Associate Technology Support Engineer" },
  { id: "123", name: "BOOTSTRAP" },
  { id: "358", name: "Backups" },
  { id: "18", name: "Banking Industry" },
  { id: "26", name: "Building Partnerships" },
  { id: "274", name: "Business & Technology Integration" },
  { id: "25", name: "Business Development" },
  { id: "342", name: "C# Software Engineer" },
  { id: "68", name: "C++ (Programming Language)" },
  { id: "277", name: "CDH" },
  { id: "103", name: "CRM" },
  { id: "120", name: "CSS" },
  { id: "205", name: "CTI" },
  { id: "31", name: "Communication" },
  { id: "14", name: "Communications" },
  { id: "66", name: "Complex Problem Solving" },
  { id: "56", name: "Composition Software Engineer" },
  { id: "201", name: "Configure" },
  { id: "23", name: "Consulting" },
  { id: "129", name: "Containerization" },
  { id: "64", name: "Critical Thinking" },
  { id: "37", name: "Customer Engineer Internship-I" },
  { id: "198", name: "Cyber Security" },
  { id: "139", name: "DATA GOVERNANCE" },
  { id: "140", name: "DATA MANAGEMENT" },
  { id: "278", name: "DATA MIGRATION" },
  { id: "141", name: "DATA SCIENCE" },
  { id: "124", name: "DEPLOYMENT" },
  { id: "91", name: "DESIGN PATTERNS" },
  { id: "71", name: "Data Structures" },
  { id: "41", name: "Design Automation Intern" },
  { id: "190", name: "Designer & Project Manager" },
  { id: "382", name: "Digital Design Engineer" },
  { id: "197", name: "Director of Technical Project Services" },
  { id: "30", name: "Diversity" },
  { id: "12", name: "Documentation" },
  { id: "279", name: "ENTERPRISE APPLICATION" },
  { id: "54", name: "ES Application Dev Engineer" },
  { id: "92", name: "EXCELLENT VERBAL AND WRITTEN COMMUNICATION SKILLS" },
  { id: "88", name: "Ecommerce" },
  { id: "385", name: "Embedded Design Engineer" },
  { id: "42", name: "Embedded Software Internship" },
  { id: "380", name: "Embedded Systems Engineer" },
  { id: "384", name: "Emulation Engineer" },
  { id: "57", name: "Encriss Software Developer Trainee - Hadoop" },
  { id: "78", name: "Engineering" },
  { id: "36", name: "Engineering Intern" },
  { id: "16", name: "English Language" },
  { id: "1", name: "Equity" },
  { id: "381", name: "FPGA Design Engineer" },
  { id: "93", name: "FRONT END DEVELOPER" },
  { id: "20", name: "Financial" },
  { id: "199", name: "Financial Services" },
  { id: "383", name: "Firmware Engineer" },
  { id: "73", name: "Front End (Software Engineering)" },
  { id: "122", name: "GIT" },
  { id: "108", name: "HTML" },
  { id: "90", name: "HTML5" },
  { id: "349", name: "Hardware Design" },
  { id: "378", name: "Hardware Engineer" },
  { id: "40", name: "Hardware Engineer Intern" },
  { id: "264", name: "Hardware Systems Architect" },
  { id: "352", name: "Hardware Testing" },
  { id: "351", name: "Hardware Troubleshooting" },
  { id: "272", name: "Harward Systems Architect - ARM Architecture" },
  { id: "179", name: "HyperText Markup Language" },
  { id: "206", name: "INCIDENT RESPONSE" },
  { id: "121", name: "IONIC" },
  { id: "408", name: "IT Helpdesk Support Engineer" },
  { id: "403", name: "IT Support Engineer" },
  { id: "404", name: "IT Support Technician" },
  { id: "27", name: "Information Technology" },
  { id: "407", name: "Information Technology Support Engineer" },
  {
    id: "412",
    name: "Information Technology Support Engineer Technical Support",
  },
  { id: "72", name: "Infrastructure" },
  { id: "19", name: "Investment Banking" },
  { id: "52", name: "Irrt Software Panel Engineer" },
  { id: "280", name: "JAVA" },
  { id: "111", name: "JAVASCRIPT" },
  { id: "94", name: "JENKINS" },
  { id: "75", name: "Java" },
  { id: "70", name: "Java (Programming Language)" },
  { id: "104", name: "Javascript" },
  { id: "51", name: "Javascript Developer - Procat" },
  { id: "55", name: "Jira Tools Developer" },
  { id: "67", name: "Judgment and Decision Making" },
  { id: "411", name: "L1 Support Engineer" },
  { id: "281", name: "LARGE-SCALE" },
  { id: "212", name: "LEADERSHIP" },
  { id: "193", name: "Land Development - Project Manager" },
  { id: "176", name: "Lead Software Developer" },
  { id: "170", name: "Lead Software Engineer" },
  { id: "79", name: "Leadership" },
  { id: "11", name: "Legal" },
  { id: "128", name: "Linux" },
  { id: "142", name: "MACHINE LEARNING" },
  { id: "213", name: "MANAGEMENT" },
  { id: "114", name: "MS SQL SERVER" },
  { id: "13", name: "Management" },
  { id: "63", name: "Mathematics" },
  { id: "35", name: "Mechanical Engineer Internship" },
  { id: "204", name: "NETWORKING" },
  { id: "353", name: "Networking" },
  { id: "127", name: "NoSQL" },
  { id: "106", name: "Node.js" },
  { id: "83", name: "NodeJS" },
  { id: "133", name: "OPERATIONS" },
  { id: "134", name: "OPERATIONS MANAGER" },
  { id: "202", name: "Operating Systems" },
  { id: "4", name: "Oral Communications Skills" },
  { id: "347", name: "Orvito Software Engineer" },
  { id: "282", name: "PEGA" },
  { id: "275", name: "PROJECT MANAGEMENT" },
  { id: "86", name: "People Management" },
  { id: "24", name: "Portfolio Management" },
  { id: "267", name: "Principal Development Engineer" },
  { id: "7", name: "Process Improvements" },
  { id: "185", name: "Product" },
  { id: "9", name: "Product Marketing" },
  { id: "82", name: "Programming Languages" },
  { id: "191", name: "Project & Implementation Manager" },
  { id: "188", name: "Project Manager" },
  { id: "189", name: "Project Manager Lead" },
  { id: "194", name: "Project Team" },
  { id: "10", name: "Publishing" },
  { id: "118", name: "Python" },
  { id: "266", name: "QE Architect" },
  { id: "21", name: "Quality" },
  { id: "28", name: "REST" },
  { id: "125", name: "RESTFUL WEB SERVICES" },
  { id: "84", name: "RESTful API" },
  { id: "34", name: "RF Engineer Internship" },
  { id: "387", name: "RTL Design Engineer" },
  { id: "105", name: "React.js" },
  { id: "60", name: "Reading Comprehension" },
  { id: "268", name: "Remote Platform Architect" },
  { id: "177", name: "Research" },
  { id: "102", name: "SALESFORCE" },
  { id: "112", name: "SASS" },
  { id: "283", name: "SDLC" },
  { id: "207", name: "SIEM" },
  { id: "110", name: "SOAP" },
  { id: "208", name: "SOC" },
  { id: "209", name: "SOP" },
  { id: "109", name: "SQL" },
  { id: "137", name: "STAKEHOLDER ENGAGEMENT" },
  { id: "74", name: "STRONG WORK ETHIC" },
  { id: "115", name: "STRUCTURED SOFTWARE" },
  { id: "5", name: "Sales" },
  { id: "8", name: "SalesForce" },
  { id: "200", name: "Security" },
  { id: "203", name: "Security Analyst" },
  { id: "174", name: "Senior Developer & Software Engineer" },
  { id: "195", name: "Senior Development Project Manager" },
  { id: "379", name: "Senior Fpga Design Engineer" },
  { id: "171", name: "Senior Lead Software Engineer" },
  { id: "192", name: "Senior Project & Program Manager" },
  { id: "196", name: "Senior Project Manager - Project Management Office" },
  { id: "344", name: "Senior Software Design Engineer" },
  { id: "346", name: "Senior Software Design Engineer & Architect" },
  { id: "167", name: "Senior Software Developer" },
  { id: "168", name: "Senior Software Developer Engineer" },
  { id: "169", name: "Senior Software Engineer" },
  { id: "343", name: "Senior Software Engineer & Software Engineer" },
  { id: "175", name: "Senior Software Engineer & UI Developer" },
  { id: "172", name: "Senior Software Engineer - Java Developer" },
  { id: "173", name: "Senior Software Engineer III" },
  { id: "269", name: "Senior System Development Engineer" },
  { id: "409", name: "Senior Technology Support Engineer" },
  { id: "355", name: "Server" },
  { id: "186", name: "Service & Offering Development" },
  { id: "3", name: "Services" },
  { id: "65", name: "Social Perceptiveness" },
  { id: "81", name: "Software" },
  { id: "43", name: "Software Developer Engineer Intern" },
  { id: "38", name: "Software Development Engineer Intern" },
  { id: "69", name: "Software Engineering" },
  { id: "187", name: "Software Eng" },
  { id: "39", name: "Software Internship" },
  { id: "178", name: "Sofware-as-a-Service" },
  { id: "62", name: "Speaking" },
  { id: "6", name: "Support" },
  { id: "265", name: "System Architect" },
  { id: "270", name: "Systems Architect" },
  { id: "135", name: "TEACHING" },
  { id: "214", name: "TEAM MANAGEMENT" },
  { id: "136", name: "TEAM PLAYER" },
  { id: "284", name: "TECHNICAL DESIGN" },
  { id: "285", name: "TEST CASE" },
  { id: "95", name: "TRANSLATING" },
  { id: "117", name: "TYPESCRIPT" },
  { id: "15", name: "Team Player" },
  { id: "271", name: "Technical Designer Architect" },
  { id: "76", name: "Technical Lead" },
  { id: "80", name: "Technical Support" },
  { id: "410", name: "Technical Support Analyst" },
  { id: "29", name: "Test" },
  { id: "406", name: "Tier- Support Engineer" },
  { id: "53", name: "Tools & IDE Software Developer" },
  { id: "22", name: "Training" },
  { id: "354", name: "Troubleshooting" },
  { id: "58", name: "UI & UX Developer & Master Trainer" },
  { id: "59", name: "UNAVAILABLE" },
  { id: "126", name: "UNIT TESTS" },
  { id: "210", name: "USE CASES" },
  { id: "96", name: "USER EXPERIENCE DESIGN" },
  { id: "97", name: "USER INTERFACE" },
  { id: "100", name: "UX" },
  { id: "85", name: "Unit Testing" },
  { id: "98", name: "VERSION CONTROL" },
  { id: "77", name: "Video" },
  { id: "116", name: "WEB SERVICES" },
  { id: "99", name: "WIREFRAME" },
  { id: "211", name: "WRITTEN AND VERBAL" },
  { id: "2", name: "Web" },
  { id: "356", name: "Windows Server" },
  { id: "235", name: "ability to adapt" },
  { id: "394", name: "ability to learn quickly" },
  { id: "294", name: "ai applications" },
  { id: "332", name: "algorithms" },
  { id: "306", name: "analytic" },
  { id: "402", name: "analytical skills" },
  { id: "166", name: "analytics" },
  { id: "154", name: "apis" },
  { id: "45", name: "application" },
  { id: "152", name: "applications" },
  { id: "361", name: "assembly" },
  { id: "216", name: "assessing" },
  { id: "398", name: "atlassian" },
  { id: "44", name: "augmented reality" },
  { id: "301", name: "automation tools" },
  { id: "319", name: "aws" },
  { id: "397", name: "azure" },
  { id: "157", name: "back-end" },
  { id: "331", name: "big data" },
  { id: "363", name: "bill of materials" },
  { id: "261", name: "build trust" },
  { id: "315", name: "building" },
  { id: "262", name: "business development" },
  { id: "130", name: "change management" },
  { id: "388", name: "cloud technology" },
  { id: "225", name: "code compliance" },
  { id: "317", name: "collaborating" },
  { id: "131", name: "collaboration" },
  { id: "254", name: "combined cycle" },
  { id: "289", name: "command line" },
  { id: "244", name: "commercial processes" },
  { id: "248", name: "communication" },
  { id: "144", name: "communication skills" },
  { id: "287", name: "complex problem solving" },
  { id: "250", name: "complex solutions" },
  { id: "295", name: "computational" },
  { id: "47", name: "computer science" },
  { id: "257", name: "conceptual thinking" },
  { id: "223", name: "consensus building" },
  { id: "230", name: "control technologies" },
  { id: "240", name: "cross-functional" },
  { id: "145", name: "css" },
  { id: "243", name: "customer focus" },
  { id: "340", name: "data analytics" },
  { id: "312", name: "data science" },
  { id: "146", name: "debug" },
  { id: "224", name: "delivering results" },
  { id: "372", name: "design" },
  { id: "184", name: "design thinking" },
  { id: "370", name: "designs" },
  { id: "215", name: "developing complex" },
  { id: "339", name: "development tools" },
  { id: "338", name: "devops" },
  { id: "391", name: "dhcp" },
  { id: "158", name: "django" },
  { id: "399", name: "dns" },
  { id: "320", name: "docker" },
  { id: "247", name: "electrical" },
  { id: "229", name: "electrical engineering" },
  { id: "227", name: "electrification" },
  { id: "258", name: "energy storage" },
  { id: "234", name: "energy storage systems" },
  { id: "368", name: "engineer" },
  { id: "369", name: "engineering analysis" },
  { id: "241", name: "excellent organizational skills" },
  { id: "359", name: "fault finding" },
  { id: "162", name: "flask" },
  { id: "303", name: "flexibility" },
  { id: "373", name: "flexible" },
  { id: "291", name: "full stack development" },
  { id: "153", name: "full-stack web development" },
  { id: "321", name: "gcp" },
  { id: "292", name: "git" },
  { id: "392", name: "great communication skills" },
  { id: "324", name: "hadoop" },
  { id: "348", name: "hardware" },
  { id: "366", name: "hardware design" },
  { id: "350", name: "hardware design engineer" },
  { id: "159", name: "html" },
  { id: "183", name: "human centred design" },
  { id: "33", name: "impact" },
  { id: "323", name: "infrastructure" },
  { id: "316", name: "innovative" },
  { id: "242", name: "integrated systems" },
  { id: "333", name: "intellectually curious" },
  { id: "165", name: "interpersonal" },
  { id: "328", name: "it infrastructure" },
  { id: "393", name: "jamf" },
  { id: "164", name: "javascript" },
  { id: "329", name: "jenkins" },
  { id: "304", name: "kubernetes" },
  { id: "255", name: "leaders" },
  { id: "302", name: "lean" },
  { id: "219", name: "marketing" },
  { id: "325", name: "mathematical programming" },
  { id: "298", name: "mathematics" },
  { id: "375", name: "mechanical engineering" },
  { id: "251", name: "meet goals" },
  { id: "220", name: "meet tight deadlines" },
  { id: "335", name: "mongodb" },
  { id: "150", name: "motivated" },
  { id: "32", name: "national security" },
  { id: "253", name: "negotiation" },
  { id: "395", name: "network" },
  { id: "390", name: "network administration" },
  { id: "362", name: "network design" },
  { id: "334", name: "node.js" },
  { id: "293", name: "object-oriented programming" },
  { id: "400", name: "operating systems" },
  { id: "326", name: "organisations" },
  { id: "367", name: "organizing" },
  { id: "237", name: "ownership" },
  { id: "310", name: "pandas" },
  { id: "396", name: "platforms" },
  { id: "337", name: "postgres" },
  { id: "228", name: "power plants" },
  { id: "160", name: "proactive" },
  { id: "314", name: "problem solving" },
  { id: "305", name: "problem-solver" },
  { id: "239", name: "problem-solving" },
  { id: "238", name: "problem-solving skills" },
  { id: "401", name: "production systems" },
  { id: "376", name: "program delivery" },
  { id: "50", name: "programming" },
  { id: "46", name: "programming skills" },
  { id: "132", name: "project delivery" },
  { id: "263", name: "proposals" },
  { id: "365", name: "prototyping" },
  { id: "143", name: "python" },
  { id: "217", name: "quote" },
  { id: "336", name: "reasoning" },
  { id: "299", name: "redis" },
  { id: "245", name: "reliable" },
  { id: "374", name: "requirements analysis" },
  { id: "231", name: "research" },
  { id: "233", name: "resilient" },
  { id: "149", name: "rest apis" },
  { id: "246", name: "result-oriented" },
  { id: "389", name: "saas" },
  { id: "252", name: "sales force" },
  { id: "341", name: "scipy" },
  { id: "221", name: "segments" },
  { id: "308", name: "service" },
  { id: "311", name: "software design" },
  { id: "307", name: "software development" },
  { id: "290", name: "software development life cycle" },
  { id: "151", name: "software development lifecycle" },
  { id: "286", name: "software development practices" },
  { id: "49", name: "software engineering" },
  { id: "313", name: "software solutions" },
  { id: "318", name: "spark" },
  { id: "327", name: "sql" },
  { id: "163", name: "stakeholders" },
  { id: "297", name: "strong communication skills" },
  { id: "371", name: "systems engineering" },
  { id: "148", name: "tech savvy" },
  { id: "260", name: "technical development" },
  { id: "236", name: "technical leadership" },
  { id: "226", name: "technical proposal" },
  { id: "259", name: "technical sales" },
  { id: "218", name: "technical solutions" },
  { id: "322", name: "technical teams" },
  { id: "309", name: "test-driven development" },
  { id: "222", name: "turbines" },
  { id: "288", name: "typescript" },
  { id: "156", name: "ui" },
  { id: "296", name: "unix" },
  { id: "364", name: "unix operating system" },
  { id: "181", name: "user experience" },
  { id: "182", name: "user interface" },
  { id: "161", name: "ux" },
  { id: "256", name: "verbal" },
  { id: "330", name: "version control" },
  { id: "155", name: "vuejs" },
  { id: "48", name: "web applications" },
  { id: "147", name: "web development" },
  { id: "300", name: "web technologies" },
  { id: "249", name: "willingness" },
  { id: "232", name: "willingness to travel" },
  { id: "377", name: "work-life balance" },
  { id: "360", name: "writing" },
];
export const RESUME = [
  "Personal Information",
  "Education",
  "Work Experience",
  "Relavant Project",
  "Skills",
];
